
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jasypt.util.password.BasicPasswordEncryptor;
import org.jasypt.util.text.BasicTextEncryptor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author CESARDOMINGO
 */
public class NCorreoU extends javax.swing.JFrame {

    Conectado conector = new Conectado();
    Connection cn = conector.conexion();
    String idusuario = "";
    public final BasicTextEncryptor textEncryptor;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form NCorreoU
     */
    public NCorreoU() {
        initComponents();
        setLocationRelativeTo(null);
        MostrarTabla();
        String[] datos = new String[4];
        this.textEncryptor = new BasicTextEncryptor();
        textEncryptor.setPassword("123");
    }

    public void Encryptar() {
        BasicPasswordEncryptor contra = new BasicPasswordEncryptor();
        String encryptedPassword = contra.encryptPassword("");
    }

    public void MostrarTabla() {
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Correo");
        modelo.addColumn("Password");
        //mostramos la tabla con sus encabezados
        TCorreoU.setModel(modelo);
        //se conecta la tabla
        String[] datos = new String[5];

        try {
            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id");
            while (rs.next()) {

                datos[0] = rs.getString("t2.id");
                datos[1] = rs.getString("t2.nombre");
                datos[2] = rs.getString("t1.correo");
                datos[3] = rs.getString("t1.pass");

                modelo.addRow(datos);
            }
            TCorreoU.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        TCorreo = new javax.swing.JTextField();
        BAgregar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TPass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCorreoU = new javax.swing.JTable();
        tfBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        BAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });

        BCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TPass))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TNombre)
                                    .addComponent(TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BCancelar)
                        .addGap(205, 205, 205)
                        .addComponent(BAgregar)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCancelar)
                    .addComponent(BAgregar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        TCorreoU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TCorreoU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TCorreoUMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TCorreoU);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        // TODO add your handling code here:
        String pas = TPass.getText();
//
//        //---------- Encriptar-------------------
        BasicTextEncryptor textEncryptor = new BasicTextEncryptor();
        textEncryptor.setPassword("123");
        String pass = textEncryptor.encrypt(pas);
        // ------------ INSERTAR USUARIO
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO usuarios(nombre) VALUES ('" + TNombre.getText() + "')");
            pst.executeUpdate();
        } catch (SQLException ex) {

        }
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO correos(correo,pass,id_usuario) "
                    + "VALUES ('" + TCorreo.getText()
                    + "','" + pass + "',(SELECT MAX(id)FROM usuarios))");
            pst.executeUpdate();
        } catch (SQLException ex) {

        }
        dispose();

    }//GEN-LAST:event_BAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeo = new DefaultTableModel();
        modeo.addColumn("ID");
        modeo.addColumn("Nombre");
        modeo.addColumn("Correo");
        modeo.addColumn("Password");
        TCorreoU.setModel(modeo);
        String buscar;
        int bandera = 0;

        String[] datos = new String[4];
        buscar = tfBuscar.getText();
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id where t2.id ='" + buscar + "'");
            while (rs.next()) {
                datos[0] = rs.getString("t2.id");
                datos[1] = rs.getString("t2.nombre");
                datos[2] = rs.getString("t1.correo");
                datos[3] = rs.getString("t1.pass");
                modeo.addRow(datos);
                bandera = 1;
            }
            TCorreoU.setModel(modeo);
            if (bandera == 0) {
                JOptionPane.showMessageDialog(null, "DATO NO ENCONTRADO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TCorreoUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCorreoUMousePressed
        // TODO add your handling code here:
        int row = TCorreoU.rowAtPoint(evt.getPoint());
        tfBuscar.setText((String) TCorreoU.getValueAt(row, 0));
    }//GEN-LAST:event_TCorreoUMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminara el correo, Continuar?", "Eliminar Correo",
                JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE a1, a2 FROM usuarios AS a1 INNER JOIN correos AS a2\n"
                        + "WHERE a1.Id=a2.id_usuario AND a1.id LIKE'" + tfBuscar.getText() + "'");
                pst.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Correo no eliminado");
                Logger.getLogger(NCorreoU.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Correo Eliminado");
        }
        /////////-----------------------Muestro la Tabla--------------------------------------------------
        DefaultTableModel limpio = new DefaultTableModel();
        limpio.addColumn("ID");
        limpio.addColumn("Nombre");
        limpio.addColumn("Correo");
        limpio.addColumn("Password");
        TCorreoU.setModel(limpio);
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id");
            while (rs.next()) {
                datos[0] = rs.getString("t2.id");
                datos[1] = rs.getString("t2.nombre");
                datos[2] = rs.getString("t1.correo");
                datos[3] = rs.getString("t1.pass");
                limpio.addRow(datos);
            }
            TCorreoU.setModel(limpio);
        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel limpio = new DefaultTableModel();
        limpio.addColumn("ID");
        limpio.addColumn("Nombre");
        limpio.addColumn("Correo");
        limpio.addColumn("Password");
        TCorreoU.setModel(limpio);
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id");
            while (rs.next()) {
                datos[0] = rs.getString("t2.id");
                datos[1] = rs.getString("t2.nombre");
                datos[2] = rs.getString("t1.correo");
                datos[3] = rs.getString("t1.pass");
                limpio.addRow(datos);
            }
            TCorreoU.setModel(limpio);
        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeo = new DefaultTableModel();
        modeo.addColumn("ID");
        modeo.addColumn("Nombre");
        modeo.addColumn("Correo");
        modeo.addColumn("Password");
        TCorreoU.setModel(modeo);
        String buscar;
        int bandera = 0;

        String[] datos = new String[4];
        buscar = tfBuscar.getText();
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id WHERE t2.id='" + buscar + "'");
            while (rs.next()) {
                datos[0] = rs.getString("t2.id");
                datos[1] = rs.getString("t2.nombre");
                datos[2] = rs.getString("t1.correo");
                String textoPlano = textEncryptor.decrypt(datos[3] = rs.getString("t1.pass"));

                modeo.addRow(datos);
                bandera = 1;

                EditarUsuario edit = new EditarUsuario();
                edit.setVisible(true);

                EditarUsuario.tfIdAjuste.setText(TCorreoU.getValueAt(0, 0).toString());
                EditarUsuario.TNombreAjuste.setText(TCorreoU.getValueAt(0, 1).toString());
                EditarUsuario.TCorreoAjuste.setText(TCorreoU.getValueAt(0, 2).toString());
                EditarUsuario.TPassAjuste.setText(textoPlano);
//                String textoPlano = textEncryptor.decrypt(Password.getText());
//                TPass.setText(textoPlano);

            }
            TCorreoU.setModel(modeo);
            if (bandera == 0) {
                JOptionPane.showMessageDialog(null, "DATO NO ENCONTRADO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        //-------------------------------------------------------------------------------
        DefaultTableModel limpio = new DefaultTableModel();
        limpio.addColumn("ID");
        limpio.addColumn("Nombre");
        limpio.addColumn("Correo");
        limpio.addColumn("Password");
        TCorreoU.setModel(limpio);
        String[] da = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT t2.id, t2.nombre, t1.correo, t1.pass FROM correos AS t1\n"
                    + "INNER JOIN usuarios AS t2 ON t1.id_usuario=t2.id");
            while (rs.next()) {
                da[0] = rs.getString("t2.id");
                da[1] = rs.getString("t2.nombre");
                da[2] = rs.getString("t1.correo");
                da[3] = rs.getString("t1.pass");
                limpio.addRow(da);
            }
            TCorreoU.setModel(limpio);
        } catch (SQLException ex) {
            Logger.getLogger(NCorreoU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NCorreoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NCorreoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NCorreoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NCorreoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NCorreoU().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JTextField TCorreo;
    public static javax.swing.JTable TCorreoU;
    private javax.swing.JTextField TNombre;
    private javax.swing.JPasswordField TPass;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables
}
